# Opinionated rustfmt configuration for Uppe.
max_width = 100
hard_tabs = false
use_small_heuristics = "Max"
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
wrap_comments = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
format_macro_matchers = true
format_macro_bodies = true
match_block_trailing_comma = true
trailing_comma = "Always"
fn_single_line = false
struct_lit_single_line = false
struct_variant_width = 40
where_single_line = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
merge_derives = true
force_multiline_blocks = true
