# Opinionated rustfmt configuration for Uppe.
max_width = 100
hard_tabs = false
use_small_heuristics = "Max"
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
struct_variant_width = 40
merge_derives = true
