
# Rustfmt configuration for the workspace
max_width = 100
hard_tabs = false
use_small_heuristics = "Max"
newline_style = "Unix"
reorder_imports = true
imports_granularity = "Crate"
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
format_macro_matchers = true
format_strings = true
