# Formatting width settings
max_width = 100
use_small_heuristics = "Max"

# Indentation & spacing
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

# Function & struct formatting
fn_call_width = 80
## fn_single_line = false  # unstable
struct_lit_width = 80
struct_variant_width = 80

# Imports & ordering
## imports_granularity = "Module"  # unstable
## group_imports = "StdExternalCrate"  # unstable
reorder_imports = true
reorder_modules = true
## imports_layout = "HorizontalVertical"  # unstable

# Wrapping & line breaking
## wrap_comments = true  # unstable
format_strings = true
match_arm_leading_pipes = "Preserve"
## match_block_trailing_comma = true  # unstable
## trailing_comma = "Vertical"  # unstable
chain_width = 80

# Miscellaneous
condense_wildcard_suffixes = true
force_explicit_abi = true
merge_derives = true
normalize_comments = true
## normalize_doc_attributes = true  # unstable
use_field_init_shorthand = true
use_try_shorthand = true
## edition = "2024"  # unstable, use 2021 for stable
