name: PeerUP Tests

on:
  push:
    paths:
      - 'crates/peerup/**'
      - '.github/workflows/peerup.yml'
  pull_request:
    paths:
      - 'crates/peerup/**'
      - '.github/workflows/peerup.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Build
        run: cargo build --package peerup
        
      - name: Test
        run: cargo test --package peerup
        
      - name: Build examples
        run: cargo build --package peerup --examples

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
          
      - name: Format check
        run: cargo fmt --all -- --check
        
      - name: Clippy
        run: cargo clippy --package peerup -- -D warnings
